import {
  Folder, Mailbox, MapPoint, Global,
  Library, Gallery, ClapperboardOpen,
  MicrophoneLarge, WalletMoney, Sale,
  Gamepad, Tv, Clouds, File, Planet, 
  StarFall2, StickerSquare, Alarm, 
  CalendarMinimalistic, DangerTriangle,
  Database, TrashBinTrash, Flag, Cup,
  Box, Gift, BenzeneRing, TestTube,
  Programming, Widget4, PieChart,
  CartLargeMinimalistic, Bag4, 
  SquareAcademicCap, BookmarkSquareMinimalistic,
  ChefHat, 

} from '@solar-icons/react';
import type { ComponentType } from 'react';

export const PROJECT_ICONS: { name: string; icon: ComponentType<{ size?: number; strokeWidth?: number }> }[] = [
  { name: 'Folder', icon: Folder },
  { name: 'Mailbox', icon: Mailbox },
  { name: 'MapPoint', icon: MapPoint },
  { name: 'Global', icon: Global },
  { name: 'Library', icon: Library },
  { name: 'Gallery', icon: Gallery },
  { name: 'ClapperboardOpen', icon: ClapperboardOpen },
  { name: 'MicrophoneLarge', icon: MicrophoneLarge },
  { name: 'WalletMoney', icon: WalletMoney },
  { name: 'Sale', icon: Sale },
  { name: 'Gamepad', icon: Gamepad },
  { name: 'Tv', icon: Tv },
  { name: 'Clouds', icon: Clouds },
  { name: 'File', icon: File },
  { name: 'Planet', icon: Planet },
  { name: 'StarFall2', icon: StarFall2 },
  { name: 'StickerSquare', icon: StickerSquare },
  { name: 'Alarm', icon: Alarm },
  { name: 'CalendarMinimalistic', icon: CalendarMinimalistic },
  { name: 'DangerTriangle', icon: DangerTriangle },
  { name: 'Database', icon: Database },
  { name: 'TrashBinTrash', icon: TrashBinTrash },
  { name: 'Flag', icon: Flag },
  { name: 'Cup', icon: Cup },
  { name: 'Box', icon: Box },
  { name: 'Gift', icon: Gift },
  { name: 'BenzeneRing', icon: BenzeneRing },
  { name: 'TestTube', icon: TestTube },
  { name: 'Programming', icon: Programming },
  { name: 'Widget4', icon: Widget4 },
  { name: 'PieChart', icon: PieChart },
  { name: 'CartLargeMinimalistic', icon: CartLargeMinimalistic },
  { name: 'Bag4', icon: Bag4 },
  { name: 'SquareAcademicCap', icon: SquareAcademicCap },
  { name: 'BookmarkSquareMinimalistic', icon: BookmarkSquareMinimalistic },
  { name: 'ChefHat', icon: ChefHat },

];

export const PROJECT_COLORS = [
  '#ed9b6d',
  '#66bb6a',
  '#64b5f6',
  '#ba68c8',
  '#ffb74d',
  '#4db6ac',
  '#e57373',
  '#9575cd',
  '#4fc3f7',
  '#fff176',
  '#f06292',
  '#aed581',
];
