import {
  Folder,
  CodeSquare,
  Buildings,
  Rocket,
  Palette,
  MusicNote,
  Camera,
  Gamepad,
  Book,
  Heart,
  Star,
  Crown,
  Star2,
  Flame,
  Bolt,
  Compass,
  Planet,
  Shield,
  Cup,
  Gift,
} from '@solar-icons/react';
import type { ComponentType } from 'react';

export const PROJECT_ICONS: { name: string; icon: ComponentType<{ size?: number; strokeWidth?: number }> }[] = [
  { name: 'Folder', icon: Folder },
  { name: 'CodeSquare', icon: CodeSquare },
  { name: 'Buildings', icon: Buildings },
  { name: 'Rocket', icon: Rocket },
  { name: 'Palette', icon: Palette },
  { name: 'MusicNote', icon: MusicNote },
  { name: 'Camera', icon: Camera },
  { name: 'Gamepad', icon: Gamepad },
  { name: 'Book', icon: Book },
  { name: 'Heart', icon: Heart },
  { name: 'Star', icon: Star },
  { name: 'Crown', icon: Crown },
  { name: 'Star2', icon: Star2 },
  { name: 'Flame', icon: Flame },
  { name: 'Bolt', icon: Bolt },
  { name: 'Compass', icon: Compass },
  { name: 'Planet', icon: Planet },
  { name: 'Shield', icon: Shield },
  { name: 'Cup', icon: Cup },
  { name: 'Gift', icon: Gift },
];

export const PROJECT_COLORS = [
  '#ed9b6d',
  '#66bb6a',
  '#64b5f6',
  '#ba68c8',
  '#ffb74d',
  '#4db6ac',
  '#e57373',
  '#9575cd',
  '#4fc3f7',
  '#fff176',
  '#f06292',
  '#aed581',
];
