import {
  Rocket,
  Lightbulb,
  Palette,
  Settings,
  BookMinimalistic,
  Target,
  Leaf,
  Bolt,
  Telescope,
  Home2,
  Bag2,
  MusicNote,
  Atom,
  Waterdrops,
  Heart,
  Star,
  Code,
  Crown,
  Planet,
  TestTube,
  Paperclip,
  StarAngle,
  Global,
  WalletMoney,
  SsdSquare,
  FolderWithFiles,
  Gift,
  CaseRound,
  SquareAcademicCap,
  BookmarkSquareMinimalistic,
  Bookmark,
  ChefHat,
  NotesMinimalistic,
  ClipboardText,
  LetterOpened,
  Mailbox,
  Library,
  Gamepad,
  Tv,
  Cloud,
  Ufo,
  CalendarMark,
  TrashBinTrash,
  Box,
  Programming
} from '@solar-icons/react';
import type React from 'react';

export const PROJECT_ICON_OPTIONS: { key: string; Icon: React.FC<{ size?: number }> }[] = [
  { key: 'rocket',    Icon: Rocket },
  { key: 'lightbulb', Icon: Lightbulb },
  { key: 'palette',   Icon: Palette },
  { key: 'settings',  Icon: Settings },
  { key: 'book',      Icon: BookMinimalistic },
  { key: 'target',    Icon: Target },
  { key: 'leaf',      Icon: Leaf },
  { key: 'bolt',      Icon: Bolt },
  { key: 'telescope', Icon: Telescope },
  { key: 'home',      Icon: Home2 },
  { key: 'bag',       Icon: Bag2 },
  { key: 'music',     Icon: MusicNote },
  { key: 'atom',      Icon: Atom },
  { key: 'water',     Icon: Waterdrops },
  { key: 'heart',     Icon: Heart },
  { key: 'star',      Icon: Star },
  { key: 'code',      Icon: Code },
  { key: 'crown',     Icon: Crown },
  { key: 'planet',    Icon: Planet },
  { key: 'testtube',  Icon: TestTube },
  { key: 'paperclip', Icon: Paperclip },
  { key: 'starangle', Icon: StarAngle },
  { key: 'global',    Icon: Global },
  { key: 'wallet',    Icon: WalletMoney },
  { key: 'ssd',       Icon: SsdSquare },
  { key: 'folder',    Icon: FolderWithFiles },
  { key: 'gift',      Icon: Gift },
  { key: 'case',      Icon: CaseRound },
  { key: 'academic',  Icon: SquareAcademicCap },
  { key: 'bookmark1', Icon: BookmarkSquareMinimalistic },
  { key: 'bookmark2', Icon: Bookmark },
  { key: 'chef',      Icon: ChefHat },
  { key: 'notes',     Icon: NotesMinimalistic },
  { key: 'clipboard', Icon: ClipboardText },
  { key: 'letter',    Icon: LetterOpened },
  { key: 'mailbox',   Icon: Mailbox },
  { key: 'library',   Icon: Library },
  { key: 'gamepad',   Icon: Gamepad },
  { key: 'tv',        Icon: Tv },
  { key: 'cloud',     Icon: Cloud },
  { key: 'ufo',       Icon: Ufo },
  { key: 'calendar',   Icon: CalendarMark },
  { key: 'trash',      Icon: TrashBinTrash },
  { key: 'box',        Icon: Box },
  { key: 'programming', Icon: Programming },
];

export const PROJECT_ICON_MAP: Record<string, React.FC<{ size?: number }>> = Object.fromEntries(
  PROJECT_ICON_OPTIONS.map(({ key, Icon }) => [key, Icon]),
);